# Facade for backward compatibility — re-exports from refactored modules

from .repositories.custom_list_repo import (
    create_custom_list,
    delete_custom_list,
    get_all_custom_lists,
    get_custom_list_by_token,
    get_custom_list_count,
)
from .repositories.indicator_repo import (
    delete_indicators,
    get_all_indicators_iter,
    get_country_stats,
    get_dns_resolution_cache_iter,
    get_domains_for_resolution,
    get_filter_options,
    get_filtered_indicators_iter,
    get_historical_stats,
    get_indicator_counts_by_type,
    get_indicators_paginated,
    get_source_counts,
    get_sources_for_indicator,
    get_sources_for_indicators_batch,
    get_unique_indicator_count,
    recalculate_scores,
    remove_old_indicators,
    save_historical_stats,
    update_dns_cache_batch,
    upsert_indicators_bulk,
)
from .repositories.job_repo import (
    clear_job_history,
    get_job_history,
    get_latest_job_times,
    log_job_end,
    log_job_start,
)
from .repositories.user_repo import (
    add_admin_profile,
    add_ldap_group_mapping,
    add_local_user,
    check_admin_credentials,
    delete_admin_profile,
    delete_ldap_group_mapping,
    delete_local_user,
    get_admin_profiles,
    get_all_users,
    get_ldap_group_mappings,
    get_profile_by_ldap_groups,
    get_user_mfa_secret,
    get_user_permissions,
    is_mfa_enabled,
    local_user_exists,
    set_admin_password,
    update_admin_profile,
    update_local_user_password,
    verify_local_user,
)
from .repositories.whitelist_repo import (
    add_api_blacklist_item,
    add_whitelist_item,
    delete_whitelisted_indicators,
    get_api_blacklist_item_by_value,
    get_api_blacklist_items,
    get_whitelist,
    remove_api_blacklist_item,
    remove_expired_blacklist_items,
    remove_whitelist_item,
    update_api_blacklist_item,
    update_whitelist_item,
)

__all__ = [
    # indicator_repo
    "delete_indicators",
    "get_all_indicators_iter",
    "get_country_stats",
    "get_dns_resolution_cache_iter",
    "get_domains_for_resolution",
    "get_filter_options",
    "get_filtered_indicators_iter",
    "get_historical_stats",
    "get_indicator_counts_by_type",
    "get_indicators_paginated",
    "get_source_counts",
    "get_sources_for_indicator",
    "get_sources_for_indicators_batch",
    "get_unique_indicator_count",
    "recalculate_scores",
    "remove_old_indicators",
    "save_historical_stats",
    "update_dns_cache_batch",
    "upsert_indicators_bulk",
    # whitelist_repo
    "add_api_blacklist_item",
    "add_whitelist_item",
    "delete_whitelisted_indicators",
    "get_api_blacklist_item_by_value",
    "get_api_blacklist_items",
    "get_whitelist",
    "remove_api_blacklist_item",
    "remove_expired_blacklist_items",
    "remove_whitelist_item",
    "update_api_blacklist_item",
    "update_whitelist_item",
    # user_repo
    "add_admin_profile",
    "add_ldap_group_mapping",
    "add_local_user",
    "check_admin_credentials",
    "delete_admin_profile",
    "delete_ldap_group_mapping",
    "delete_local_user",
    "get_admin_profiles",
    "get_all_users",
    "get_ldap_group_mappings",
    "get_profile_by_ldap_groups",
    "get_user_mfa_secret",
    "get_user_permissions",
    "is_mfa_enabled",
    "local_user_exists",
    "set_admin_password",
    "update_admin_profile",
    "update_local_user_password",
    "verify_local_user",
    # job_repo
    "clear_job_history",
    "get_job_history",
    "get_latest_job_times",
    "log_job_end",
    "log_job_start",
    # custom_list_repo
    "create_custom_list",
    "delete_custom_list",
    "get_all_custom_lists",
    "get_custom_list_by_token",
    "get_custom_list_count",
]
