apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tfa
  labels:
    app: threat-feed-aggregator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: threat-feed-aggregator
  template:
    metadata:
      labels:
        app: threat-feed-aggregator
    spec:
      securityContext:
        runAsUser: 1001
        fsGroup: 0
      containers:
        - name: tfa
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $key, $value := .Values.env }}
            {{- if $value }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name: GUNICORN_WORKER
              value: "1"
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app/threat_feed_aggregator/data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
